[package]
name = "compile_with_bazel"
version = "0.0.0"

# Mandatory (or Cargo tooling is unhappy)
[lib]
path = "fake_lib.rs"

[dependencies]
aho-corasick = "=0.7.15"
lazy_static = "=1.4.0"
proc-macro2 = "=1.0.33"
quote = "=1.0.10"
syn = "=1.0.82"

[dev-dependencies]
quickcheck = "=1.0.3"

[package.metadata.raze]
genmode = "Remote"
workspace_path = "//util/import/raze"
gen_workspace_prefix = "rules_rust_util_import"
rust_rules_workspace_name = "rules_rust"
package_aliases_dir = "."
default_gen_buildrs = true