[package]
name = "rules_rust_examples_complex_sys"
version = "0.0.1"

[[bin]]
name = "rules_rust_examples_complex_sys"
path = "src/main.rs"

[dependencies]
git2 = "=0.13.12"
openssl = "=0.10.32"
openssl-sys = "=0.9.60"

[package.metadata.raze]
workspace_path = "//sys/complex/raze"
genmode = "Remote"
gen_workspace_prefix = "complex_sys"
rust_rules_workspace_name = "rules_rust"
package_aliases_dir = "raze"
default_gen_buildrs = true

[package.metadata.raze.crates.openssl-sys.'*']
# build.rs file: https://github.com/sfackler/rust-openssl/blob/master/openssl-sys/build/main.rs
build_data_dependencies = [
    "@openssl//:openssl",
    "@openssl//:gen_dir",
]
data_attr = "[\"@openssl//:openssl\"]"
additional_deps = ["@openssl//:openssl"]
    [package.metadata.raze.crates.openssl-sys.'*'.buildrs_additional_environment_variables]
        OPENSSL_DIR="$(execpath @openssl//:gen_dir)"
        OPENSSL_STATIC="1"

[package.metadata.raze.crates.libssh2-sys.'0.2.20']
build_data_dependencies = ["@openssl"]
